(() => {
  const core=window.KasokoBooking, C=window.KASOKO_CATALOG||{}, qs=new URLSearchParams(location.search); let lang=(typeof localStorage!=='undefined'&&localStorage.getItem('kt-lang'))||'en';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const serviceLabels={en:{safari:'Safari',tour:'Tour / excursion',hotel:'Hotel / lodge',flight:'Flight ticket',bus:'Bus ticket',ferry:'Ferry ticket',train:'Train ticket',transfer:'Transfer / private ride',custom:'Combined trip'},sw:{safari:'Safari ya hifadhi',tour:'Ziara / excursion',hotel:'Hoteli / loji',flight:'Tiketi ya ndege',bus:'Tiketi ya basi',ferry:'Tiketi ya feri',train:'Tiketi ya treni',transfer:'Usafiri binafsi',custom:'Safari yenye huduma nyingi'}};
  const fields=['service','destination','origin','startDate','endDate','tripType','adults','children','childAges','infants','rooms','roomType','mealPlan','travelClass','operator','time','style','currency','budget','notes','name','phone','email','contactMethod'];
  let step=1;
  function dateMin(){const d=new Date();const tz=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Dar_es_Salaam',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);return tz}
  function formData(){const f=$('#booking-form'), d={}; fields.forEach(k=>{const el=f.elements[k]; if(el) d[k]=el.value}); d.adults=Number(d.adults||0);d.children=Number(d.children||0);d.infants=Number(d.infants||0);d.rooms=Number(d.rooms||1);d.addons=$$('input[name="addons"]:checked').map(x=>x.value);d.consent=$('#consent').checked;d.language=lang; return d}
  function showStep(n){step=n;$$('[data-form-step]').forEach(x=>x.classList.toggle('active',Number(x.dataset.formStep)===n));$$('[data-step]').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)<=n)); window.scrollTo({top:document.querySelector('.booking-card').offsetTop-90,behavior:'smooth'}); if(n===3) renderSummary()}
  function errorText(errors){const e=errors[0]; if(!e)return ''; const el=$(`[name="${e.field}"]`);el?.focus();return e.message}
  function validatePhase(phase){const errors=core.validate(formData(),lang,phase); const box=phase==='contact'? $('[data-form-error]'): $('[data-details-error]'); if(box)box.textContent=errorText(errors); return !errors.length}
  function populate(){const s=$('#service'), selected=qs.get('service')||'safari'; const opts=core.types.map(x=>`<option value="${x}">${serviceLabels[lang][x]}</option>`).join('');s.innerHTML=opts;s.value=core.types.includes(selected)?selected:'safari'; const item=qs.get('item'); const found=[...(C.destinations||[]),...(C.hotels||[])].find(x=>x.id===item); if(found){const foundName=found.name?.en||found.name; const foundLocation=typeof found.location==='string'?found.location:(found.location?.en||''); $('#destination').value=foundName; if(foundLocation) $('#destination').value+=foundName.toLowerCase().includes(foundLocation.toLowerCase())?'':' — '+foundLocation; } else if(qs.get('region')) { $('#destination').value=qs.get('region'); } $('#startDate').min=dateMin(); $('#endDate').min=dateMin(); const addons=['safari','tour','hotel','flight','bus','ferry','train','transfer']; $('#addon-list').innerHTML=addons.map(x=>`<label class="check"><input type="checkbox" name="addons" value="${x}" /><span>${serviceLabels[lang][x]}</span></label>`).join(''); updateVisibility()}
  function updateVisibility(){const s=$('#service').value; $$('.hotel-only').forEach(e=>e.hidden=s!=='hotel');$$('.ticket-only').forEach(e=>e.hidden=!core.tickets.includes(s)); $('#origin-wrap').hidden=!(core.tickets.includes(s)||s==='transfer'); $('#trip-type-wrap').hidden=!core.tickets.includes(s); $('#end-wrap').hidden=!(s==='hotel'||core.tickets.includes(s)); if(s==='hotel')$('#tripType').value='return'; if(core.tickets.includes(s)&&!['oneway','return'].includes($('#tripType').value))$('#tripType').value='oneway'; if(s!=='hotel'&&!core.tickets.includes(s)){$('#endDate').value='';$('#tripType').value='';} }
  function renderSummary(){const d=formData(); $('#summary-box').innerHTML=core.summary(d,lang).map(([k,v])=>`<div><span>${k}</span><b>${String(v).replace(/[<>]/g,'')}</b></div>`).join('')}
  function requestId(){return (crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2)).replace(/[^a-zA-Z0-9-]/g,'').slice(0,60)}
  function whatsappUrl(d, ref){const addons=(d.addons||[]).map(x=>serviceLabels.en[x]||x).join(', '); const text=`Kasoko booking request ${ref||''}\nName: ${d.name}\nService: ${serviceLabels.en[d.service]}\nDestination: ${d.destination}\nDates: ${d.startDate}${d.endDate?' to '+d.endDate:''}\nPeople: ${d.adults} adults, ${d.children} children, ${d.infants} infants\nAdditional services: ${addons||'None'}\nPhone: ${d.phone}`; return 'https://wa.me/255789515769?text='+encodeURIComponent(text)}
  async function submit(ev){ev.preventDefault(); const d=formData(); const errors=core.validate(d,lang); if(errors.length){const contact=['name','phone','email','contactMethod','consent'].includes(errors[0].field);showStep(contact?2:1); const box=contact?$('[data-form-error]'):$('[data-details-error]');if(box)box.textContent=errorText(errors);return} const btn=$('button[type="submit"]');btn.disabled=true;btn.textContent=lang==='sw'?'Inatuma…':'Sending…'; const ref='KST-'+requestId().slice(0,20).toUpperCase(); try{const response=await fetch((window.KASOKO_CONFIG?.bookingEndpoint)||'/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...d,requestId:ref,website:''})}); const result=await response.json(); if(!response.ok||!result.ok||result.status!=='request_received'||result.bookingConfirmed!==false) throw new Error(result.error||'delivery_failed'); $('#booking-result').hidden=false; $('#booking-result').innerHTML=`<div class="success-icon">✓</div><h2>${lang==='sw'?'Ombi limepokelewa':'Request received'}</h2><p>${lang==='sw'?'Namba yako ya ombi ni':'Your request reference is'} <strong>${result.reference}</strong>. ${lang==='sw'?'Kasoko itakuwasiliana baada ya kuangalia nafasi na bei ya sasa.':'Kasoko will contact you after checking live availability and price.'}</p><div class="result-actions"><a class="btn primary" target="_blank" rel="noopener" href="${whatsappUrl(d,result.reference)}">${lang==='sw'?'Fungua WhatsApp':'Open WhatsApp'}</a><button class="btn ghost" type="button" data-download>${lang==='sw'?'Pakua muhtasari':'Download summary'}</button></div>`; $('#booking-form').hidden=true; $('#booking-result').querySelector('[data-download]').addEventListener('click',()=>downloadSummary(d,result.reference)); }catch(err){btn.disabled=false;btn.textContent=lang==='sw'?'Tuma ombi':'Send request'; $('#booking-result').hidden=false; $('#booking-result').innerHTML=`<div class="warning-icon">!</div><h2>${lang==='sw'?'Ombi bado halijatumwa':'Request not sent yet'}</h2><p>${lang==='sw'?'Haikuwezekana kutuma ombi mtandaoni kwa sasa. Pakua rasimu au tumia WhatsApp hapa chini.':'We could not send the request online right now. Download a draft or use WhatsApp below.'}</p><div class="result-actions"><a class="btn primary" target="_blank" rel="noopener" href="${whatsappUrl(d,ref)}">${lang==='sw'?'Tuma kupitia WhatsApp':'Send via WhatsApp'}</a><button class="btn ghost" type="button" data-download>${lang==='sw'?'Pakua rasimu':'Download draft'}</button></div>`;$('#booking-result').querySelector('[data-download]').addEventListener('click',()=>downloadSummary(d,ref));}}
  function downloadSummary(d,ref){const lines=[`Kasoko Safaris & Tours — ${ref}`,...core.summary(d,'en').map(x=>x[0]+': '+x[1])];const blob=new Blob([lines.join('\n')],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`kasoko-booking-${ref}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  $('#service').addEventListener('change',updateVisibility); $('#children').addEventListener('input',()=>{if(Number($('#children').value)===0)$('#childAges').value=''}); $$('[data-next]').forEach(b=>b.addEventListener('click',()=>{if(Number(b.dataset.next)===2&&validatePhase('details'))showStep(2);else if(Number(b.dataset.next)===3&&validatePhase('contact'))showStep(3)})); $$('[data-prev]').forEach(b=>b.addEventListener('click',()=>showStep(Number(b.dataset.prev)))); $('#booking-form').addEventListener('submit',submit); populate(); document.addEventListener('kasoko:language',event=>{lang=event.detail;const current=$('#service').value;populate();$('#service').value=current;updateVisibility()});
})();
